version: '3.1'
services:
    redis:
        image: redis:latest
        ports:
        - "6379:6379"
    web:
        image: odoo:14.0
        depends_on:
            - db
        ports:
            - "8069:8069"
    db:
        image: postgres:13
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRESS_USER=odoo
        ports:
            - "5432:5432"